### ISSUE TITLE
希望侧边栏宽度可以再调节到更窄

### ISSUE THREAD

**Issue by Jvcon** [RabbitPair/colorful_sidepanel_tabs_extension#15]
**Is your feature request related to a problem? Please describe.**
当我在14寸笔记本使用的时候，侧边栏宽度还是太长了，整体可利用空间不大

**Describe the solution you'd like**
支持调整的最小宽度再小一点

**Comment by ymlluo** [comment]
这个是chrome的限制，目前改不了，等chrome支持的时候会第一时间跟进的，感谢反馈~
