### ISSUE TITLE
扩展是否是默认打开一个分组?如果是,是否支持设置?该处理逻辑导致无法折叠全部分组。

### ISSUE THREAD

**Issue by oneseral** [RabbitPair/colorful_sidepanel_tabs_extension#17]

**Comment by ymlluo** [comment]
选项  「高级标签组」中有一项「标签组折叠行为」，上一个版本默认值是「显示当前组并折叠其他组」，需要修改为 「使用浏览器默认设置」 这样才可以折叠全部分组。新版本修改成「使用浏览器默认设置」了，但是如果之前已经设置过的不会自动修改，你可以手动修改一下试试
