### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by BeneFischl** [RabbitPair/colorful_sidepanel_tabs_extension#18]
I'm right handed, so I prefer the vertitab on the left side of the screen.
Thanks for your time

**Comment by ymlluo** [comment]
Thank you for your feedback! Regarding your preference to display VertiTab on the left side of the screen, we’d like to clarify a few details:  

- **Are you using Microsoft Edge?**  
  If so, we’re sorry to inform you that Edge’s extension framework does not currently support adjusting the position of extensions in the sidebar.  

- **If you are using Chrome**, you can follow these steps to move the side panel to the left:  
  1. Open Chrome on your computer.  
  2. Click on **“More”** (the three dots in the top-right corner).  
  3. Select **“Settings”**.  
  4. Navigate to the **“Appearance”** section.  
  5. Under **“Side panel”**, enable **“Show on left”**.

For more details, you can refer to Chrome’s official support page:  
[Manage Side Panel - Chrome Help](https://support.google.com/chrome/answer/13156494?hl=en#zippy=%2Cmanage-side-panel).  

If you have further questions or use a different browser, feel free to let us know! 😊
