### ISSUE TITLE
B站点击视频弹出新标签后，首页会自动往下滚动。

### ISSUE THREAD

**Issue by kylin30** [RabbitPair/colorful_sidepanel_tabs_extension#19]
**Describe the bug**
在B站首页点击视频会打开新标签显示视频，此时返回首页所在标签会发现首页自动向下滚动了一段距离。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 22h2
 - Browser: Chrome
 - Version 131.0.6778.86

**Additional context**

**Comment by ymlluo** [comment]
感谢反馈，我修一下

Kei ***@***.***> 于2024年11月27日周三 19:38写道：

**Comment by ymlluo** [comment]
v2.14.0 published and fixed
