### ISSUE TITLE
能关闭这个功能吗？我不想订阅高级功能只想使用侧边栏服务，画中画按钮一直挂在那边很烦

### ISSUE THREAD

**Issue by imyeeming** [RabbitPair/colorful_sidepanel_tabs_extension#22]
**Website address**

----

**Additional context**

**Comment by ymlluo** [comment]
新版本已经在审核了，最晚明天就可以更新了，然后就可以隐藏了，抱歉~

**Comment by imyeeming** [comment]
好的谢谢

Ymlluo ***@***.***> 于 2024年12月27日周五 下午12:31写道：

**Comment by ymlluo** [comment]
2.14.2 已发布。你可以在 设置-画中画-视频上的浮动按钮 关闭就可以了

**Comment by imyeeming** [comment]
解决了，谢谢你的协助

Ymlluo ***@***.***> 于 2024年12月27日周五 下午6:14写道：
