### ISSUE TITLE
move group tab or tab suport

### ISSUE THREAD

**Issue by saixia** [RabbitPair/colorful_sidepanel_tabs_extension#3]
1. Drag VertiTab group tab or tab can with chrome  group tab or tab when tags sort by Tab index;
2. Clicking VertiTab group Tab syschronized with the opening and closing with browser tab groups;

**Comment by ymlluo** [comment]
Ok, I'll add it as soon as possible.

**Comment by saixia** [comment]
Bug：Cannot Support drag-and-drop sorting of tabs when tab in groups

**Comment by ymlluo** [comment]
I reproduced this problem and released a new version that has been submitted for review.

**Comment by ymlluo** [comment]
this feature has been added . close this issue

**Comment by saixia** [comment]
Thank you for your quick response. Could you add Wechat pay or Alipay as donation payment toptions?

**Comment by ymlluo** [comment]
First of all, thank you for your support. It is your feedback that makes this extension better and better. Now the extension has added a premium version, which supports payment through WeChat. If you think the premium version is helpful to you, you can [pre-order it](https://www.rabbitpair.com/pricing).
But if you don’t need the premium version, please don’t pre-order it. Please help recommend the extension to your friends.
Please also provide more suggestions for this extension. Thank you again for your support
