### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by TwBridges** [RabbitPair/colorful_sidepanel_tabs_extension#4]
**Describe the bug**
There is a set minimum width of the side bar and it would be nice if there was an option or configuration to make it smaller

**To Reproduce**
1. open sidebar
2. try to shrink sidebar

**Expected behavior**
I would expect to be able to make the side bar as big or small as I'd like and have everything expand downard

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ymlluo** [comment]
I'm very sorry, this is a restriction of chrome, and it can't be modified at the moment, but hopefully chrome can be corrected in my lifetime 😅, maybe you can use the "page sidebar" for the time being.
