### ISSUE TITLE
Bookmark navigation

### ISSUE THREAD

**Issue by TwBridges** [RabbitPair/colorful_sidepanel_tabs_extension#5]
**Is your feature request related to a problem? Please describe.**
Let me say I love love love this extension, however I have a lot of bookmarks with a lot of hierarchy that makes it easier for me to navigate and find the resource I am looking for. The way bookmarks are currently set up makes it very hard to use in my scenario, but also in general. 

**Describe the solution you'd like**

Currently I am using another extension for my bookmarks that makes traversal easier. 

I can think of 2 solutions that might improve this extension.

1.) Replace the positions of bookmarks and Recently Closed Tabs (RCT would become an Icon and bookmarks would sit next to open tabs then show bookmarks in a tree hierarchy structure similar to screenshots.

2.) add a configuration that allows for a user to decide between RCT and Bookmarks and then similar implementation of bookmarks as above.

**Describe alternatives you've considered**
https://extensions.redeviation.com/

**Additional context**
![image](https://github.com/user-attachments/assets/8b888f4c-5b95-4ac7-a4cd-178f0caf32ba)

**Comment by ymlluo** [comment]
Thank you for your feedback! Your request is on our roadmap. We're planning to add tree tabs and bookmark features soon. You'll be able to choose between "tabs," "recently closed tabs," and "bookmarks" in the toolbar tabs, and we'll also let you show tabs, history, bookmarks, etc., in the search results. These features are coming soon, so stay tuned. You can follow this issue, and I'll update you here once these features are released.

**Comment by ymlluo** [comment]
@TwBridges The new version v2.70 has been approved and released, and this feature has been added . You can update the extension to use this feature
