### ISSUE TITLE
move tab to specific group in Sidebar

### ISSUE THREAD

**Issue by Wkjlovec** [RabbitPair/colorful_sidepanel_tabs_extension#6]
Thank you for the amazing work you’ve done on this Chrome extension. It has greatly enhanced my browsing experience!
Description
I would like to propose a feature that allows users to long-press a tab in the sidebar to move it into different groups. This feature would be particularly useful when using fullscreen mode (F11)(maximising the screen to get rid of the top toolbar is one of the most use for this awseome extension), where the top tabs are not visible.

**Comment by ymlluo** [comment]
In the next version, I will first add the feature to move tabs into groups by right-clicking. The ability to drag tabs into groups will be introduced later.

**Comment by Wkjlovec** [comment]
Thank you for your quick response! . I’m looking forward to trying it out!
Best,

**Comment by ymlluo** [comment]
@Wkjlovec  The new version v2.70 has been approved and released, and this feature has been added to the context menu. You can update the extension to use this feature
