### ISSUE TITLE
Number of grouped display tabs and Export tab data

### ISSUE THREAD

**Issue by oneseral** [RabbitPair/colorful_sidepanel_tabs_extension#8]
# Number of grouped display tabs
+ Display the number of tabs for each group after the group name

# Export tab data

+ Support selecting one or more groups
+ Support selecting specified pages

**Comment by ymlluo** [comment]
### Thank you for your feedback

I appreciate your input and would like to address your concerns:

#### Upcoming Feature
- The "Number of grouped display tabs" feature will be added in the next version.

#### Regarding Exporting Groups and Tabs

To better assist you, I need some additional information:

1. **Use Cases**
   - Could you provide specific scenarios where you'd use this feature?
   - Note: If your goal is to restore group and tab information, our current "snapshot" feature in the options settings already provides import and export functionality.

2. **Feature Placement**
   - Where would you prefer this feature to be located?
     - Sidebar's multi-select menu
     - Background options page

3. **Export Data Requirements**
   - What information do you need when exporting group and tab data?
   - Suggested data points:
     - Groups: name, color
     - Tabs: title, link
   - Is this sufficient, or do you need more details?
   - Do you have a preferred format?
     - JSON
     - Plain text
     - Markdown
     - XML
     - Other (please specify)

Your feedback will help us tailor this feature to best meet your needs. Thank you for helping us improve our product!

**Comment by ymlluo** [comment]
> Display the number of tabs for each group after the group name

This feature has been implemented and released in v2.11.0. Since I haven't heard back from you, this issue has been closed first
